name: Compile Server

on: push

jobs:
  pack:
    name: Get 1.16.2 server
    runs-on: macOS-latest
    steps:
      - name: Prepare env
        run: |
          brew cask install java
      - name: Getting BuildTools
        run: |
          mkdir server
          cd server && wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Building Server
        run: |
          cd server && java -jar BuildTools.jar

      - name: Upload file
        uses: actions/upload-artifact@master
        with:
          name: spigot
          path: server/spigot-1.16.2.jar

      - name: Upload to cowtransfer
        run: |
          wget https://jerrita.cn/mac/transfer
          chmod +x transfer
          ./transfer cow -s -p 64 server/spigot-1.16.2.jar | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
